
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModelSample_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModelSample.ModelInput sampleData = new MLModelSample.ModelInput()
            {
                ImageSource = @"E:\GitWork\ml.net-with-opencvsharp\Src\Sample\Data\Image\Front\.151602556167.png",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModelSample.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"ImageSource: {@"E:\GitWork\ml.net-with-opencvsharp\Src\Sample\Data\Image\Front\.151602556167.png"}");


            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
